language: python

python:
  - "3.10"

env:
  - SECRET_KEY='$$^HKHSASK*(!U(__2056523"

before_install:
  - sudo apt-get update
  - sudo apt-get install language-pack-es
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 14

services:
  - postgresql

addons:
  postgresql: 14

  apt:
    packages:
      - postgresql-14-postgis-2.3

before_script:
  - psql -U postgres -c "create extension postgis"

install:
  - pipenv install

script:
  - python manage.py test
