name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        db: [postgres]
        python-version: [3.10.5]
        include:
          - db: postgres
            db_user: 'kartoza'
            db_password: '@Support1999'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Start PostgreSQL
      if: matrix.db == 'postgres'
      run: |
        sudo systemctl start postgresql.service
        sudo -u postgres createuser -s kartoza
    - name: Install GDAL Libraries
      run: |
        sudo apt-get install binutils libproj-dev gdal-bin
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Grant Database Privileges
      run: |
        psql -c 'GRANT ALL PRIVILEGES ON ALL TABLES in schema PUBLIC TO kartoza;'
    - name: Run Tests
      env:
        SECRET_KEY: ${{secrets.SECRET_KEY}}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{secrets.DB_HOST}}
        DB_PORT: ${{secrets.DB_PORT}}
        DB_ENGINE: ${{secrets.DB_ENGINE}}
      run: |
        python manage.py test --keepdb Kartoza
